### ISSUE TITLE
Launch pad link not working? 

### ISSUE THREAD

**Issue by mcm113** [lukso-network/network-configs#10]
The link for https://launchpad.l15.lukso.network is not working.

**Comment by Hugoo** [comment]
Hi mcm13,

Thanks for opening the issue.

The L15 Testnet is under active development and a few services may go down while they are upgraded and fixed.

It is recommended to keep up with latest changes in the #validators channel of our Discord server.

https://discord.com/channels/359064931246538762/809394861160529940/903340347206271047

**Comment by mxmar** [comment]
We have prepared change that will expose maintenance page instead of not working prod launchpad URL. It's already done and we will deploy it to leave proper feedback for visitors :) But thank you @mcm113 for your notice.
